logo: # add logo name
title: Shekou's Skin Care
description: > # Your skin is your largest organ and requires routine care, just like the rest of your body.
  Take care of it and pamper yourself with Shekou's Skincare!
  Enjoy a wide variety of luxurious services in a relaxing and rejuvenating environment.
  You'll leave feeling refreshed and renewed.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: bgimage.jpg
banner-title: Shekou's Skin Care
banner-desc: > #
  Your skin is your largest organ and requires routine care, just like the rest of your body.
  Take care of it and pamper yourself with Shekou's Skincare!
  Enjoy a wide variety of luxurious services in a relaxing and rejuvenating environment.
  You'll leave feeling refreshed and renewed.

# Author settings
author-pic: shekoufeh.jpg
author-name: Shekoufeh
about-author: Beautiful skin does not come from make up, it's from a good aesthetician and high quality product!
email: 320 Seven Springs Way suit 250, Brentwood, TN  37027
phone: (615)-400-2528 # your pnone number
website:

# Social link
google_url:    # add url link
twitter_url:   # add url link
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  https://www.facebook.com/shekou.safari?ref=br_rs

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
